//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP_01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int UserID { get; set; }
        public Nullable<int> StudyGroup { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
    
        public virtual StudyGroup StudyGroup1 { get; set; }
        public virtual User User { get; set; }
    }
}
