//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP_01_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReport
    {
        public int ID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<System.DateTime> TestDATE { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public int TestDuration { get; set; }
        public int TotalQuestions { get; set; }
        public int CorrectAnswers { get; set; }
        public int Grade { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual Test Test { get; set; }
    }
}
